### ISSUE TITLE
freeze splash screen

### ISSUE THREAD

**Issue by ysus** [njleonzhang/generator-gulp-ionic#3]
Hola, saludos:
the generator is perfect, work great, but  when i  run it in  my device android the second y followed times is freeze in the splash screen (load after 20 or 30 seconds sometimes), sorry for my bad english.

**Comment by njleonzhang** [comment]
@ysus  sorry, I cannot understand you very clearly, but you mentioned splash screen stuck. So I check the configuration of the splash screen. For demo, we decide to [make splash auto hide by default](https://github.com/njleonzhang/generator-gulp-ionic/commit/decec747be464062e9d45cfe4262757ef9aa2c3c). Would you please update the generate and try again? If your issue persists, please describe the reproduce method step by step, so that we can know how to reproduce it. Thanks for your attention and help.

**Comment by ysus** [comment]
thnk! work perfect, but i have another problem, when i install with npm install -g generator-gulp-ionic  don´t install all files in the generators folder. don´t install script-base.js and util.js y template folder too. i have to installed manually. 

thanks for you help

**Comment by njleonzhang** [comment]
@ysus Tnx for your info. We will check this issue.
@storkyeh Can you help to look into this issue?

**Comment by storkyeh** [comment]
@ysus I fixed the issue, please take a try. Thanks for your attention and help.

**Comment by ysus** [comment]
thnks! work perfect
