### ISSUE TITLE
Can't install on windows, instalation stucked

### ISSUE THREAD

**Issue by pabloalcaraz** [njleonzhang/generator-gulp-ionic#9]
Hi,

I can't install it on windows runing npm install -g generator-gulp-ionic, the console says the next:

npm install -g generator-gulp-ionic
[               ...] \ extract:lodash: verb gentlyRm don't care about contents; nuking ...AppData\Roaming\npm\node_modules\.staging\lodash-58e8b95c\node_modules

I've tried in different computers without success.

**Comment by njleonzhang** [comment]
Can you install other npm package globally?

**Comment by njleonzhang** [comment]
Maybe you need check your npm environment. https://github.com/npm/npm/issues/13722

**Comment by pabloalcaraz** [comment]
Hi,

Yes, i've installed a lot of packages with -g. I updated the node package and still fails.

npm 4.3.0
node 6.10.0

**Comment by njleonzhang** [comment]
OK, I never tried on windows. It may take days to fix this issue due to my full calendar. So can you help to debug?

**Comment by pabloalcaraz** [comment]
I tested on mac and works perfectly, but not on windows, maybe line jumps, slashes or file names too long but Im lost at this moment. So I will use it on mac.

**Comment by njleonzhang** [comment]
@pabloalcaraz  I have debuged this issue on `Windows` using tool `Process Monitor`.
The stuck is caused by `invalid file name`. So I am sorry to tell you that this lib can not work on `Windows`.
BTW, ionic2 is released, maybe you should try ionic2. 

![qq 20170312224241](https://cloud.githubusercontent.com/assets/13174059/23832720/a663a0c2-0775-11e7-8b65-06ac5cae05f8.png)
